### ISSUE TITLE
Widget Only Displays Once?

### ISSUE THREAD

**Issue by WilfulTravesty** [fightforthefuture/redalert-widget#1]
The red alert widget is not working on http://www.ipdb.org, nor on sub-pages like http://www.ipdb.org/machine.cgi?id=2684

It only displays once, then not again for any page.

Is that the expected behavior?

**Comment by kenmickles** [comment]
@WilfulTravesty that was the expected behavior (because it's how [our other widget](https://github.com/fightforthefuture/battleforthenet-widget) works), but I think you're right, and that's kind of confusing. So I updated this widget to show on subsequent page views until the close button is clicked.
